#!/bin/bash
function advertise {
    key=$1
    value=$2
    echo _CONDOR_$key="$value"
    export _CONDOR_$key="$value"

}

for FS in \
    ams.cern.ch \
    atlas.cern.ch \
    cms.cern.ch \
    connect.opensciencegrid.org \
    gwosc.osgstorage.org \
    icecube.opensciencegrid.org \
    ligo-containers.opensciencegrid.org \
    nexo.opensciencegrid.org \
    oasis.opensciencegrid.org \
    singularity.opensciencegrid.org \
    snoplus.egi.eu \
    spt.opensciencegrid.org \
    stash.osgstorage.org \
    veritas.opensciencegrid.org \
    xenon.opensciencegrid.org \
; do
    FS_CONV=`echo "$FS" | sed 's/[\.-]/_/g'`
    FS_ATTR="HAS_CVMFS_$FS_CONV"
    RESULT="False"
    
    # keep the filesystems mounted
    ls -l /cvmfs/$FS/ >/dev/null 2>&1

    if [ -e /cvmfs/$FS/. ]; then
        RESULT="True"
        # add the revision
        REV_ATTR="CVMFS_${FS_CONV}_REVISION"
        REV_VAL=`/usr/bin/attr -q -g revision /cvmfs/$FS/. 2>/dev/null`
        
        # oasis.opensciencegrid.org needs extra checks
        if [ "x$FS" = "xoasis.opensciencegrid.org" ]; then
            if ! cat /cvmfs/oasis.opensciencegrid.org/osg/sw/module-init.sh >/dev/null 2>&1; then
                REV_VAL=""
            fi
            if ! cat /cvmfs/oasis.opensciencegrid.org/sbgrid/update.details >/dev/null 2>&1; then
                REV_VAL=""
            fi
        fi

        # oasis.opensciencegrid.org needs extra checks
        if [ "x$FS" = "xoasis.opensciencegrid.org" ]; then
            if ! cat /cvmfs/oasis.opensciencegrid.org/osg/sw/module-init.sh >/dev/null 2>&1; then
                REV_VAL=""
            fi
            if ! cat /cvmfs/oasis.opensciencegrid.org/sbgrid/update.details >/dev/null 2>&1; then
                REV_VAL=""
            fi
        fi

        # stash.osgstorage.org needs extra checks
        if [ "x$FS" = "xstash.osgstorage.org" ]; then
            if ! cat /cvmfs/stash.osgstorage.org/user/bbockelm/public/testfile >/dev/null 2>&1; then
                REV_VAL=""
            fi
        fi
        
        # veritas.opensciencegrid.org
        if [ "x$FS" = "xveritas.opensciencegrid.org" ]; then
            if ! cat /cvmfs/veritas.opensciencegrid.org/py2-v1/setup.sh >/dev/null 2>&1; then
                REV_VAL=""
            fi
        fi

        # now we are ready to advertise
        if [ "x$REV_VAL" != "x" ]; then
            # make sure it is an integer
            if [ "$REV_VAL" -eq "$REV_VAL" ] 2>/dev/null; then
                advertise $FS_ATTR "$RESULT"
                advertise $REV_ATTR "$REV_VAL"

            fi
        else
            # unable to determine revision - this is common on sites which re-export CVMFS
            # via for example NFS locally. Advertise availability.
            advertise $FS_ATTR "$RESULT"

        fi
    fi
done

# if it looks like we have CVMFS, make sure the START expression knows that
#if [ -e /cvmfs ]; then
#    export GLIDEIN_VALIDATION_EXPR="HAS_CVMFS_oasis_opensciencegrid_org && HAS_CVMFS_singularity_opensciencegrid_org && HAS_CVMFS_stash_osgstorage_org"
#fi

# update timestamp?
TS_ATTR="CVMFS_oasis_opensciencegrid_org_TIMESTAMP"
TS_VAL=`(cat /cvmfs/oasis.opensciencegrid.org/osg/update.details  | egrep '^Update unix time:' | sed 's/.*: //') 2>/dev/null`
if [ "x$TS_VAL" != "x" ]; then
    # make sure it is an integer
    if [ "$TS_VAL" -eq "$TS_VAL" ] 2>/dev/null; then
        advertise $TS_ATTR "$TS_VAL" 
    fi
fi

# operating system

# /etc/issue works most of the time, but there are exceptions
OS_NAME=`cat /etc/issue | head -n1 | awk '{print $1;}' | tr '[:lower:]' '[:upper:]'`

if [ "X$OS_NAME" = "xUBUNTU" ]; then
    OS_VERSION=`cat /etc/issue | head -n1 | awk '{print $2;}'`
elif [ -e /etc/debian_version ]; then
    OS_NAME="DEBIAN"
    OS_VERSION=`cat /etc/debian_version`
elif [ "X$OS_NAME" = "xFEDORA" ]; then
    OS_VERSION=`cat /etc/issue | head -n1 | awk '{print $3;}'`
elif [ -e /etc/redhat-release ]; then
    OS_NAME="RHEL"
    OS_VERSION=`cat /etc/redhat-release | grep -o -E ' [0-9]+.[0-9]+'`
elif [ -e /etc/rocks-release ]; then
    OS_NAME="RHEL"
    OS_VERSION=`cat /etc/rocks-release | grep -o -E ' [0-9]+.[0-9]+'`
elif [ -e /etc/SuSE-release ]; then
    OS_NAME="SUSE"
    OS_VERSION=`cat /etc/SuSE-release | grep VERSION | grep -o -E ' [0-9]+'`
fi

# remove spaces/tabs in the version
OS_VERSION=`echo $OS_VERSION | sed 's/[ \t]//g'`

# remove / in the version
OS_VERSION=`echo $OS_VERSION | sed 's/\//_/g'`

# we only want major version numbers
OS_VERSION=`echo $OS_VERSION | sed 's/[\.-].*//'`

if [ "x$OS_NAME" = "x" ]; then
    OS_NAME="Unknown"
fi
if [ "x$OS_VERSION" = "x" ]; then
    OS_VERSION="Unknown"
fi

# kernel
OS_KERNEL=`uname -r`
if [ "x$OS_KERNEL" = "x" ]; then
    OS_KERNEL="Unknown"
fi

advertise OSGVO_OS_NAME "$OS_NAME"
advertise OSGVO_OS_VERSION "$OS_VERSION"
advertise OSGVO_OS_STRING "$OS_NAME $OS_VERSION"
advertise OSGVO_OS_KERNEL "$OS_KERNEL"

# cpu info
CPU_MODEL=`cat /proc/cpuinfo | grep -i "^model name" | head -n 1 | sed -r 's/[a-zA-Z \t]+:[ ]*//'`
advertise OSGVO_CPU_MODEL "$CPU_MODEL"

# some cpu flags HTCondor is not yet advertising
for FLAG in `cat /proc/cpuinfo | egrep -i ^flags | head -n 1 | sed -r 's/[a-zA-Z \t]+:[ ]*//'`; do
    if (echo "$FLAG" | egrep "avx512") >/dev/null 2>&1; then
        advertise has_$FLAG "True"
    fi
done

# if we are in Singularity, override HTCondor's OsSys* vars with the
# default container details
if [ "x$OSG_SINGULARITY_REEXEC" = "x1" ]; then
    # RHEL is CentOS in HTCondor
    if [ "x$OS_NAME" = "xRHEL" ]; then
        OS_NAME="CentOS"
    fi
    advertise OpSysLongName "Singularity Container - $OS_NAME $OS_VERSION"
    advertise OpSysAndVer "${OS_NAME}${OS_VERSION}"
    advertise OpSysName "$OS_NAME"
    advertise OpSysShortName "$OS_NAME"
    advertise OpSysMajorVer "$OS_VERSION"
    advertise OpSysVer "${OS_VERSION}00"
fi
